spring:
  application:
    name: customer-service-service

server:
  port : 8080
          
endpoints:
  jmx:
    enabled: false

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    
info:
  version: ${APP_VERSION:0.0.1}
  name: ${spring.application.name}                  