server:
  port: ${SERVER_PORT:5017}

eureka:
 instance:
   hostname: ${SERVER_HOST:localhost}
   preferIpAddress: false
   leaseRenewalIntervalInSeconds: 5
 client:
   registerWithEureka: true
   fetchRegistry: true
   registryFetchIntervalSeconds: 5
   enabled: ${EUREKA_CLIENT_ENABLED:true}
   leaseRenewalIntervalInSeconds: 5
   healthcheck:
     enabled: true
   serviceUrl:
     defaultZone: ${EUREKA_URL:http://${SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:5012}/eureka/}
 server:
   waitTimeInMsWhenSyncEmpty: 0
   
elastic:
  client:
    authenticated: false
    protocol: http
    elasticHostConfigs:
      -  
        host: 1.2.3
        port: 123
      - 
        host: a.b.c
        port: 567