eureka:
 instance:
   hostname: ${SERVER_HOST:localhost}
   preferIpAddress: false
   leaseRenewalIntervalInSeconds: 5
   health-check-url-path: /actuator/health
   metadataMap:
      password: ${DEFAULT_PASSWORD:admin}
 client:
   registerWithEureka: true
   fetchRegistry: true
   registryFetchIntervalSeconds: 5
   enabled: ${EUREKA_CLIENT_ENABLED:true}
   leaseRenewalIntervalInSeconds: 5
   healthcheck:
     enabled: true
   serviceUrl:
     defaultZone: ${EUREKA_URL:http://${SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:3082}}/eureka/
 server:
   waitTimeInMsWhenSyncEmpty: 0

---
spring:
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:shared/
         